services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - NEO4J_URI=${NEO4J_URI:-bolt://host.docker.internal:7687}
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - USE_PARALLEL_RUNTIME=${USE_PARALLEL_RUNTIME:-false}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-}

